### PR TITLE
Build Biopython 1.77

### PR DESCRIPTION
**Pull request by chebizarro**
As per the build instruction, the updates to the .travis and appveyor configuration files for wheel building

### CODE REVIEW

**Comment by peterjc** [comment]
Fingers crossed - this should just work, the "fun" comes when the wheel infrastructure needs updating (e.g. adding a new Python)

**Comment by peterjc** [comment]
Note on a pull request like this, the wheel upload is expected to fail:

```
WARNING: secret API key missing: skipping package upload
```

Once this is merged to the wheel repository master branch, it should just work (TM).

**Comment by peterjc** [comment]
And once this is merged and the wheels are done, before pushing them to PyPI we should have a day or so to ask the community for some quick testing...

**Comment by peterjc** [comment]
Ah. Failing on Python 2.7 and 3.5 makes perfect sense since we dropped support for them.

You'll need to remove their matrix entries in ``appveyor.yml`` and ``.travis.yml`` - should be obvious, ask if not.

**Comment by peterjc** [comment]
I wonder why TravisCI didn't run this pull request...

https://travis-ci.org/github/biopython/biopython-wheels/pull_requests

**Comment by peterjc** [comment]
Ah. Looks like something is broken with the TravisCI setup, got something useful out of TravisCI after manually triggering a build, "Build config did not create any job"

https://travis-ci.org/github/biopython/biopython-wheels/requests?requestId=214135280

**Comment by peterjc** [comment]
A shame TravisCI/GitHub seemed to have treated this as a silent failure. My only guess right now is tabs versus spaces in ``.travis.yml`` meaning I merged this prematurely?

**Comment by peterjc** [comment]
Nope, all spaces. Maybe this is an earlier problem that I missed until now...

**Comment by peterjc** [comment]
There's a TravisCI yaml validator/linter which we should probably try at this point - I don't have it installed, and don't have time right no to do that. Can you Chris?

**Comment by peterjc** [comment]
On the bright side, the Windows wheels from AppVeyor are starting to appear on RackSpace 👍

**Comment by chebizarro** [comment]
Possibly a consequence of dropping the previous Python versions? Seems related to this:
https://travis-ci.community/t/build-config-did-not-create-any-jobs/4650
When I add a python version to each job, the job matrix is generated correctly when using https://config.travis-ci.com/explore
I'll make another pull request.

**Pull request merged**
