### PR TITLE
Add sklearn Rackspace credentials

### PR DESCRIPTION
**Pull request by matthew-brett**

### CODE REVIEW

**Comment by peterjc** [comment]
Lovely, thank you. Can I copy those as is into ``appveyor.yml`` or do they need to be done separately?

**Comment by matthew-brett** [comment]
Needs to be done separately, but first you need to decide which account will be building the appveyor wheels.  In this case the encryption is per-account rather than per-project.

**Comment by peterjc** [comment]
We'll be using the Biopython group account on AppVeyor, i.e. https://ci.appveyor.com/project/biopython/biopython-wheels/history

P.S. The TravisCI built wheels are already starting to show up on the rackspace storage, thank you 👍

**Comment by matthew-brett** [comment]
Can you give me access to the account so I can make a encrypted key for it?  Feel free to revoke after I've done that.

**Comment by peterjc** [comment]
Sure - I've emailed you about that (not 100% which account you need access too).

**Pull request merged**
