### PR TITLE
Try building Biopython 1.79

### PR DESCRIPTION
**Pull request by JoaoRodrigues**

### CODE REVIEW

**Comment by peterjc** [comment]
You should now have write (and thus merge permissions) here via the "releases" team

**Comment by peterjc** [comment]
Interesting, a new mode of failure:

> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

We can probably just re-run the failed TravisCI element after waiting say 10 mins after everything else finishes? We may want to set a concurrency limit?

New question: Do you have sufficient rights on TravisCI to do that (may work via GitHub permissions, I forget)?

**Comment by peterjc** [comment]
OK, we need to wait six hours and then re-try.

**Comment by peterjc** [comment]
Ah. Looks like the 100 anonymous container image pull requests limit per six hours is per IP address, and thus pot luck with TravisCI. See e.g.

https://blog.addressfinder.io/quick-fix-for-dockers-toomanyrequests-you-have-reached-your-pull-rate-limit-from-travis-64410327e8e6

**Comment by peterjc** [comment]
Separately the ARM64 builds are failing (see #11), looks like a broken Debian depencency when this is run from ``config.sh``:

```
$ apt-get install -y sudo locales language-pack-en-base
```

```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  language-pack-en
The following NEW packages will be installed:
  language-pack-en language-pack-en-base locales sudo
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 4160 kB of archives.
After this operation, 20.9 MB of additional disk space will be used.
Ign:1 http://ports.ubuntu.com/ubuntu-ports xenial-security/main arm64 locales all 2.23-0ubuntu11.2
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 language-pack-en-base all 1:16.04+20160627 [451 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 language-pack-en all 1:16.04+20161009 [145 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main arm64 sudo arm64 1.8.16-0ubuntu1.10 [347 kB]
Err:1 http://ports.ubuntu.com/ubuntu-ports xenial-security/main arm64 locales all 2.23-0ubuntu11.2
  404  Not Found [IP: 91.189.91.38 80]
Fetched 943 kB in 1s (636 kB/s)
E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/g/glibc/locales_2.23-0ubuntu11.2_all.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

That is indeed currently a 404 link, but ``locales_2.23-0ubuntu11.3_all.deb`` exists. I presume it will be sorted in a few days, but if not it doesn't need to delay the Biopython release.

**Comment by JoaoRodrigues** [comment]
Sorry - had to be AFK for a while.

I'll wait for the 6 hours to pass and then just make an empty push here. To answer your question:

>New question: Do you have sufficient rights on TravisCI to do that (may work via GitHub permissions, I forget)?

Nope!

**Comment by peterjc** [comment]
It need not be an empty commit, but a bump to ``048c4cdd717e9eb56affaaf66275b90d7dc274e9`` with the Tutorial LaTex fix.

**Comment by peterjc** [comment]
(Note the bump for the Latex fix is irrelevant for the wheels because they don't including the tutorial source or PDF)

**Comment by JoaoRodrigues** [comment]
Running 👍

**Comment by JoaoRodrigues** [comment]
Ack - same error... Any way around this?

**Comment by peterjc** [comment]
There are two options outlined on https://github.com/matthew-brett/multibuild/issues/410 - or we go ahead without any Linux wheels? Conda-forge will be an option for pre-compiled Linux binaries, but still plenty of Linux users via pip will end up unwittingly trying to compile it from source... I fear that will make more work for us.

Are you familiar with Docker Hub? I'm not (yet).

**Comment by peterjc** [comment]
I think we can merge this PR anyway - and see how many wheels we're missing

**Comment by JoaoRodrigues** [comment]
Between this issue and the debian package that is missing, we're probably missing quite a few wheels unfortunately.

I did work with DockerHub a few years ago, but wouldn't we have to modify the source of `multibuild` ourselves, to change the line defining the docker containers? That was my understanding from the linked issue.

**Comment by JoaoRodrigues** [comment]
Another option I see is to move to Github Actions for this. There is [cibuildwheel](https://github.com/pypa/cibuildwheel), which seems to be quite simple to setup. It's used by `scikit-learn` and `matplotlib`, so definitely an established tool.

**Comment by peterjc** [comment]
The Debian issue is ARM specific, currently niche compared to AMD64.

**Comment by peterjc** [comment]
Building on a PR will not cache any of the wheels, so I've merged this.

So that you can try rebuilding the expected AMD64 failures - do you see the Biopython repository under your TravisCI permissions? It does seem to work off the GitHub permissions, maybe it needs a refresh?

**Comment by JoaoRodrigues** [comment]
"Trigger Build" is grayed out for me. Do we use travis `.com` or `.org`?

**Comment by peterjc** [comment]
macOS done:

https://anaconda.org/multibuild-wheels-staging/biopython/files?version=1.79

Can you see the "restart" button here? Although do it on the children, not top level:

https://travis-ci.org/github/biopython/biopython-wheels/builds/773071185 (this PR)

Update: Or more relevant, the merged commit on the master which will upload wheels:

https://travis-ci.org/github/biopython/biopython-wheels/builds/773144347

**Comment by peterjc** [comment]
First Linux wheel done on a retry - tedious but this will _probably_ suffice for this release.

**Comment by peterjc** [comment]
We're on borrowed time here:

> "Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com."

**Comment by peterjc** [comment]
I've periodically tried re-running some of the i686 (32 bit) and AMD64 Linux wheels - so far they've all hit the Docker limit.

(*Update - a couple worked, but others restarted around the same time failed - luck of the draw in the worker node IP address I guess*)

**Comment by peterjc** [comment]
Progress on the Linux wheels:

* [X] 32 bit Python 3.6
* [x] 64 bit Python 3.6
* [x] 32 bit Python 3.7
* [x] 64 bit Python 3.7
* [x] 32 bit Python 3.8
* [x] 64 bit Python 3.8
* [X] 32 bit Python 3.9
* [X] 64 bit Python 3.9

https://anaconda.org/multibuild-wheels-staging/biopython/files?version=1.79

**Comment by JoaoRodrigues** [comment]
OK, I can restart jobs now. Don't know what changed, but now I do see the restart button! Will keep an eye on the remaining jobs. I guess ARM64 won't be done because of that missing deb.

**Comment by JoaoRodrigues** [comment]
All linux + mac wheels built! All Win wheels also seem to be complete but they are not in the anaconda page?

**Comment by peterjc** [comment]
Yay. See #9 for where to find the Windows wheels.

**Comment by JoaoRodrigues** [comment]
Got it - shall I just copy them manually from Appveyor?

**Comment by peterjc** [comment]
Yes - it would be nicer if the macOS, Linux and Windows wheels all got staged in the same place, but it doesn't really matter for getting them up onto PyPI.

**Comment by peterjc** [comment]
Cross reference https://github.com/conda-forge/biopython-feedstock/pull/33

**Pull request merged**
